version: "3.8"
services:
  app:
    image: instaloader
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
    build: .
    volumes:
      - ./output:/app   # host_folder:docker_folder